
name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PRODJECT_ID: ${{secrets.VERCEL_PRD_ID}}

on: 
  push:
    branches:
      - main

jobs:
  Deploy_development:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install npm
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          registry-url: 'https://registry.npmjs.org/' 

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=deployment --token=${{secrets.VERCEL_ACCESS_TOKEN}}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{secrets.VERCEL_ACCESS_TOKEN}}

      - name: Deploy Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{secrets.VERCEL_ACCESS_TOKEN}}
  
